{{- if or .Values.config.apiPassword .Values.config.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moniple-agent.fullname" . }}-secrets
  labels:
    {{- include "moniple-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.apiPassword }}
  prometheus-password: {{ .Values.config.apiPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.apiKey }}
  moniple-api-key: {{ .Values.config.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
